# NumPy Practice

This notebook offers a set of exercises for different tasks with NumPy.

It should be noted there may be more than one different way to answer a question or complete an exercise.

Exercises are based off (and directly taken from) the quick introduction to NumPy notebook.

Different tasks will be detailed by comments or text.

For further reference and resources, it's advised to check out the [NumPy documentation](https://numpy.org/devdocs/user/index.html).

And if you get stuck, try searching for a question in the following format: "how to do XYZ with numpy", where XYZ is the function you want to leverage from NumPy.

In [10]:
# Import NumPy as its abbreviation 'np'
import numpy as np 

In [11]:
# Create a 1-dimensional NumPy array using np.array()
ar1 = np.array([1,2,3]) 

# Create a 2-dimensional NumPy array using np.array()
ar2 = np.array([[1,2,3],[4,5,6]])

# Create a 3-dimensional Numpy array using np.array()
ar3 = np.array([[1,2,3],[4,5,6],[7,8,9]])


Now we've you've created 3 different arrays, let's find details about them.

Find the shape, number of dimensions, data type, size and type of each array.

In [12]:
# Attributes of 1-dimensional array (shape, 
# number of dimensions, data type, size and type)
print(ar1.dtype)
print(ar1.ndim)
print(ar1.shape)

int32
1
(3,)


In [13]:
# Attributes of 2-dimensional array
print(ar2.dtype)
print(ar2.ndim)
print(ar2.shape)

int32
2
(2, 3)


In [14]:
# Attributes of 3-dimensional array
print(ar3.dtype)
print(ar3.ndim)
print(ar3.shape)

int32
2
(3, 3)


In [15]:
row,col = ar2.shape 
print(row)
print(col)

2
3


In [16]:
# Import pandas and create a DataFrame out of one
# of the arrays you've created
import pandas as pd 
ar2 = np.array([[1,2,3],[4,5,6]])
df = pd.DataFrame()
print(df)

Empty DataFrame
Columns: []
Index: []


In [17]:
# Create an array of shape (10, 2) with only ones
ar_ones = np.ones((10,2))
print(ar_ones)

[[1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]]


In [18]:
# Create an array of shape (7, 2, 3) of only zeros
ar_zeros = np.zeros((7,2,3))
print(ar_zeros)

[[[0. 0. 0.]
  [0. 0. 0.]]

 [[0. 0. 0.]
  [0. 0. 0.]]

 [[0. 0. 0.]
  [0. 0. 0.]]

 [[0. 0. 0.]
  [0. 0. 0.]]

 [[0. 0. 0.]
  [0. 0. 0.]]

 [[0. 0. 0.]
  [0. 0. 0.]]

 [[0. 0. 0.]
  [0. 0. 0.]]]


In [19]:
# Create an array within a range of 0 and 100 with step 3
ar_range = np.arange(101)
print(ar_range)

[  0   1   2   3   4   5   6   7   8   9  10  11  12  13  14  15  16  17
  18  19  20  21  22  23  24  25  26  27  28  29  30  31  32  33  34  35
  36  37  38  39  40  41  42  43  44  45  46  47  48  49  50  51  52  53
  54  55  56  57  58  59  60  61  62  63  64  65  66  67  68  69  70  71
  72  73  74  75  76  77  78  79  80  81  82  83  84  85  86  87  88  89
  90  91  92  93  94  95  96  97  98  99 100]


In [20]:
# Create a random array with numbers between 0 and 10 of size (7, 2)
ar_random1 = np.random.randint(0,11,size = (7,2))
print(ar_random1)

[[1 4]
 [8 7]
 [9 3]
 [4 0]
 [6 6]
 [2 0]
 [9 7]]


In [21]:
# Create a random array of floats between 0 & 1 of shape (3, 5)
ar_random2 = np.random.rand(3,5)
print(ar_random2)

[[0.29029944 0.72551496 0.94290793 0.97857757 0.04289467]
 [0.97543279 0.8435163  0.13980611 0.25794081 0.37158558]
 [0.43727447 0.60560627 0.76643206 0.44338319 0.73621439]]


In [22]:
# Set the random seed to 42
import random
ar_random3 = random.seed(42)
print(ar_random3)
# Create a random array of numbers between 0 & 10 of size (4, 6)
ar_random3 = np.random.randint(0,11,size=(4,6))
print(ar_random3)

None
[[ 5  9  6  4 10  1]
 [ 9  1  2  2  9  5]
 [ 2  7  1  6  8 10]
 [ 9  9 10  1  9  3]]


Run the cell above again, what happens?

Are the numbers in the array different or the same? Why do think this is?

In [23]:
# Create an array of random numbers between 1 & 10 of size (3, 7)
# and save it to a variable
ar_random4 = np.random.randint(1,11, size = (3,7))
print(ar_random4)
# Find the unique numbers in the array you just created
print(np.unique(ar_random4))
#print(unique_numbers)

[[4 9 2 5 9 1 9]
 [5 9 7 4 7 2 4]
 [1 9 5 7 2 2 9]]
[1 2 4 5 7 9]


In [24]:
# Find the 0'th index of the latest array you created
print(ar_random4.flat[0])

4


In [25]:
# Get the first 2 rows of latest array you created
print(ar_random4[:2, :])

[[4 9 2 5 9 1 9]
 [5 9 7 4 7 2 4]]


In [26]:
# Get the first 2 values of the first 2 rows of the latest array
print(ar_random4[:, :2])

[[4 9]
 [5 9]
 [1 9]]


In [27]:
# Create a random array of numbers between 0 & 10 and an array of ones
# both of size (3, 5), save them both to variables
ar_random5 = np.random.randint(0,11, size = (3,5))
print(ar_random5)
ar_random6 = np.random.randint(0,11, size = (3,5))
print(ar_random6)

[[ 2  6  7  7 10]
 [10 10  6  7  8]
 [ 4  5  2  5  1]]
[[10  8  2  6  9]
 [ 0  6  2  3  3]
 [ 2  1  9  7  4]]


In [28]:
# Add the two arrays together
ar_random7 = ar_random5 + ar_random6
print(ar_random7)

[[12 14  9 13 19]
 [10 16  8 10 11]
 [ 6  6 11 12  5]]


In [29]:
# Create another array of ones of shape (5, 3)
ar_1 = np.ones((5,3))
print(ar_1)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [30]:
# Try add the array of ones and the other most recent array together
# print(ar_random7 + ar_1) It's Error 

When you try the last cell, it produces an error. Why do think this is?

How would you fix it?

In [31]:
# Create another array of ones of shape (3, 5)
ar_1s = np.ones((3,5))
print(ar_1s)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


In [32]:
# Subtract the new array of ones from the other most recent array
ar_random8 = ar_random7 + ar_1s
print(ar_random8)

[[13. 15. 10. 14. 20.]
 [11. 17.  9. 11. 12.]
 [ 7.  7. 12. 13.  6.]]


In [33]:
# Multiply the ones array with the latest array
ar_random9 = np.multiply(ar_1s,ar_random8)
print(ar_random9)

[[13. 15. 10. 14. 20.]
 [11. 17.  9. 11. 12.]
 [ 7.  7. 12. 13.  6.]]


In [34]:
# Take the latest array to the power of 2 using '**'
ar_random10 = ar_random9 ** 2
print(ar_random10)

[[169. 225. 100. 196. 400.]
 [121. 289.  81. 121. 144.]
 [ 49.  49. 144. 169.  36.]]


In [35]:
# Do the same thing with np.square()
ar_radnom11 = np.square(ar_random9)
print(ar_radnom11)

[[169. 225. 100. 196. 400.]
 [121. 289.  81. 121. 144.]
 [ 49.  49. 144. 169.  36.]]


In [36]:
# Find the mean of the latest array using np.mean()
print(np.mean(ar_radnom11))


152.86666666666667


In [37]:
# Find the maximum of the latest array using np.max()
print(np.max(ar_radnom11))

400.0


In [38]:
# Find the minimum of the latest array using np.min()
print(np.min(ar_radnom11))

36.0


In [39]:
# Find the standard deviation of the latest array
import statistics
print(np.std(ar_radnom11))

94.01196141390142


In [40]:
# Find the variance of the latest array
print(np.var(ar_radnom11))

8838.24888888889


In [41]:
# Reshape the latest array to (3, 5, 1)
ar_random12 = np.reshape(ar_radnom11, (3 ,5 ,1))
print(ar_random12)

[[[169.]
  [225.]
  [100.]
  [196.]
  [400.]]

 [[121.]
  [289.]
  [ 81.]
  [121.]
  [144.]]

 [[ 49.]
  [ 49.]
  [144.]
  [169.]
  [ 36.]]]


In [42]:
# Transpose the latest array
print(np.transpose(ar_random12))

[[[169. 121.  49.]
  [225. 289.  49.]
  [100.  81. 144.]
  [196. 121. 169.]
  [400. 144.  36.]]]


What does the transpose do?

In [43]:
# Create two arrays of random integers between 0 to 10
# one of size (3, 3) the other of size (3, 2)


In [44]:
# Perform a dot product on the two newest arrays you created


In [45]:
# Create two arrays of random integers between 0 to 10
# both of size (4, 3)


In [46]:
# Perform a dot product on the two newest arrays you created


It doesn't work. How would you fix it?

In [47]:
# Take the latest two arrays, perform a transpose on one of them and then perform 
# a dot product on them both


Notice how performing a transpose allows the dot product to happen.

Why is this?

Checking out the documentation on [`np.dot()`](https://docs.scipy.org/doc/numpy/reference/generated/numpy.dot.html) may help, as well as reading [Math is Fun's guide on the dot product](https://www.mathsisfun.com/algebra/vectors-dot-product.html).

Let's now compare arrays.

In [48]:
# Create two arrays of random integers between 0 & 10 of the same shape
# and save them to variables


In [49]:
# Compare the two arrays with '>'


What happens when you compare the arrays with `>`?

In [50]:
# Compare the two arrays with '>='


In [51]:
# Find which elements of the first array are greater than 7


In [52]:
# Which parts of each array are equal? (try using '==')


In [53]:
# Sort one of the arrays you just created in ascending order


In [54]:
# Sort the indexes of one of the arrays you just created


In [55]:
# Find the index with the maximum value in one of the arrays you've created


In [56]:
# Find the index with the minimum value in one of the arrays you've created


In [57]:
# Find the indexes with the maximum values down the 1st axis (axis=1)
# of one of the arrays you created


In [58]:
# Find the indexes with the minimum values across the 0th axis (axis=0)
# of one of the arrays you created


In [59]:
# Create an array of normally distributed random numbers


In [60]:
# Create an array with 10 evenly spaced numbers between 1 and 100


## Extensions

For more exercises, check out the [NumPy quickstart tutorial](https://numpy.org/doc/stable/user/quickstart.html). A good practice would be to read through it and for the parts you find interesting, add them into the end of this notebook.

Pay particular attention to the section on broadcasting. And most importantly, get hands-on with the code as much as possible. If in dobut, run the code, see what it does.

The next place you could go is the [Stack Overflow page for the top questions and answers for NumPy](https://stackoverflow.com/questions/tagged/numpy?sort=MostVotes&edited=true). Often, you'll find some of the most common and useful NumPy functions here. Don't forget to play around with the filters! You'll likely find something helpful here.

Finally, as always, remember, the best way to learn something new is to try it. And try it relentlessly. If you get interested in some kind of NumPy function, asking yourself, "I wonder if NumPy could do that?", go and find out.